---
- name: update web servers
  hosts: all
  become: yes
  tasks:
  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest
      update_cache: yes
      cache_valid_time: 3600
